name: martinjohnny
favicon: null
layout_spectrum: 0.4581252774223685
typography_spectrum: 0.32269770302809775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#201013'
    - '#d0c3ca'
    - '#633631'
    - '#b19aac'
    - '#7d709b'
  brandStrength: 0.6945679662749171
  lightness: 0.8729184509720653
  saturation: 0.8697865621652454
  rhythmicContrast: 0.75
purpose: []
